networks:
  default:
    name: proxy
    external: true

services:
  sonarr:
    container_name: sonarr    
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/void/data:/data
      - ./container_data/sonarr/config:/config
    networks:
      default:
        ipv4_address: 172.20.0.201
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.local.xerogravity.space`) || Host(`sonarr.ts.xerogravity.space`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"