networks:
  default:
    name: tk-proxy
    external: true

services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TORRENTING_PORT=6881
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /mnt/void/data/torrents:/data/torrents
      - ./container_data/qbittorrent/config:/config
    labels:
      - "traefik.enable=true"
      # middleware
      - "traefik.http.middlewares.qbittorrent.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.qbittorrent.headers.customrequestheaders.Referer="
      - "traefik.http.middlewares.qbittorrent.headers.customrequestheaders.Origin="
      # router
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.local.xerogravity.space`) || Host(`qbittorrent.ts.xerogravity.space`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.routers.qbittorrent.middlewares=qbittorrent"
      - "traefik.http.routers.qbittorrent.service=qbittorrent"
      # service
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.services.qbittorrent.loadbalancer.passhostheader=false"
  
  seedbox:
    container_name: seedbox
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TORRENTING_PORT=6881
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - /mnt/void/seedbox/torrents:/data/torrents
      - ./container_data/seedbox/config:/config
    labels:
      - "traefik.enable=true"
      # middleware
      - "traefik.http.middlewares.seedbox.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.seedbox.headers.customrequestheaders.Referer="
      - "traefik.http.middlewares.seedbox.headers.customrequestheaders.Origin="
      # router
      - "traefik.http.routers.seedbox.tls=true"
      - "traefik.http.routers.seedbox.rule=Host(`seedbox.local.xerogravity.space`)"
      - "traefik.http.routers.seedbox.entrypoints=https"
      - "traefik.http.routers.seedbox.middlewares=seedbox"
      - "traefik.http.routers.seedbox.service=seedbox"
      # service
      - "traefik.http.services.seedbox.loadbalancer.server.port=8080"
      - "traefik.http.services.seedbox.loadbalancer.passhostheader=false"