networks:
  default:
    name: tk-proxy
    external: true

services:
  saas:
    container_name: composecraft
    depends_on:
    - mongodb
    environment:
      CORE_ONLY: true
      MONGODB_URI: mongodb://mongo:${DB_PASS}@db
      SECRET_KEY: changeme
      URL: http://localhost:3000
    image: composecraft/composecraft:latest
    labels:
      traefik.enable: true
      traefik.http.routers.composecraft.entrypoints: https
      traefik.http.routers.composecraft.rule: Host(`composecraft.local.xerogravity.space`)
      traefik.http.routers.composecraft.service: composecraft
      traefik.http.routers.composecraft.tls: true
      traefik.http.services.composecraft.loadbalancer.server.port: 5001
    ports:
    - 3000:3000
  mongodb:
    container_name: composecraft-mongodb
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_ROOT_USERNAME: mongo
    image: mongo:latest
    volumes:
    - type: bind
      source: ./container_data/mongo/db
      target: /data/db
      read_only: false
