services:
  threadfin:
    container_name: threadfin
    environment:
      PGID: 1001
      PUID: 1001
      TZ: America/Los_Angeles
    image: fyb3roptik/threadfin
    ports:
    - 34400:34400
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./container_data/threadfin/conf
      target: /home/threadfin/conf
      read_only: false
    - type: bind
      source: ./container_data/threadfin/temp
      target: /tmp/threadfin
      read_only: false
