networks:
  default:
    name: proxy
    external: true

services:  
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./container_data/prowlarr/config:/config
    network_mode: "container:gluetun"