networks:
  default:
    name: tk-proxy
    external: true

services:
  tdarr:
    container_name: tdarr
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
    devices:
    - /dev/dri:/dev/dri
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      PGID: 1000
      PUID: 1000
      TZ: Asia/Kolkata
      UMASK_SET: 2
      ffmpegVersion: 6
      inContainer: true
      internalNode: true
      nodeName: Matrix
      serverIP: 0.0.0.0
      serverPort: 8266
      webUIPort: 8265
    image: ghcr.io/haveagitgat/tdarr:latest
    labels:
      traefik.enable: true
      traefik.http.routers.tdarr.entrypoints: https
      traefik.http.routers.tdarr.middlewares: secure-middlewares@file
      traefik.http.routers.tdarr.rule: Host(`tdarr.local.xerogravity.space`)
      traefik.http.routers.tdarr.service: tdarr
      traefik.http.routers.tdarr.tls: true
      traefik.http.services.tdarr.loadbalancer.server.port: 8265
    ports:
    - 8265:8265
    - 8266:8266
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./data/server
      target: /app/server
      read_only: false
    - type: bind
      source: ./data/configs
      target: /app/configs
      read_only: false
    - type: bind
      source: ./data/logs
      target: /app/logs
      read_only: false
    - type: bind
      source: /mnt/void/data/media
      target: /media
      read_only: false
    - type: bind
      source: ./data/transcode_cache
      target: /temp
      read_only: false
