version: "3.8"

networks:
  dns:
    driver: bridge
    external: true

services:
  bind9:
    container_name: bind9
    image: bind9:9.18
    networks:
      - dns
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 127.0.0.1:953:953/tcp
    restart: always