version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - /mnt/blackhole/data/media:/data/media
    extra_hosts:
      - host.docker.internal:host-gateway

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    user: 1000:1000
    restart: unless-stopped
    networks:
      - chilflix_frontend
      - chilflix_backend
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    volumes:
      - ./jellyseerr-config:/app/config

networks:
  chilflix_frontend:
    driver: bridge
    external: true
  chilflix_backend:
    driver: bridge
    external: true
