networks:
  default:
    name: tk-proxy
    external: true

services:
  sabnzbd:
    container_name: sabnzbd
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Asia/Kolkata
    image: lscr.io/linuxserver/sabnzbd:latest
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.entrypoints: https
      traefik.http.routers.sabnzbd.rule: Host(`sabnzbd.local.xerogravity.space`)
      traefik.http.routers.sabnzbd.service: sabnzbd
      traefik.http.routers.sabnzbd.tls: true
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
    ports:
    - 8084:8080
    restart: unless-stopped
    volumes:
    - type: bind
      source: /mnt/void/data/usenets
      target: /data/usenets
      read_only: false
    - type: bind
      source: ./container_data/sabnzbd/config
      target: /config
      read_only: false
