services:
  bind9:
    image: internetsystemsconsortium/bind9:9.19
    container_name: bind9
    network_mode: 'host'
    volumes:
      - ./data/config:/etc/bind
      - ./data/cache:/var/cache/bind
      - ./data/lib/:/var/lib/bind
      - ./data/log/:/var/log
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 127.0.0.1:953:953/tcp
    restart: always