networks:
  default:
    name: proxy
    external: true

services:
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf:latest
    restart: unless-stopped
    ports:
      - 8085:8080
    volumes:
      - ./container_data/stirling-pdf/tessdata:/usr/share/tessdata
      - ./container_data/stirling-pdf/configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.tls=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`stirling-pdf.local.xerogravity.space`)"
      - "traefik.http.routers.stirling-pdf.entrypoints=https"
      - "traefik.http.routers.stirling-pdf.service=stirling-pdf"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"