networks:
  default:
    name: tk-proxy
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./container_data/traefik/acme.json:/acme.json
      - ./container_data/traefik/config.yml:/config.yml:ro
      - ./container_data/traefik/traefik.yml:/traefik.yml:ro
    labels:
      - "traefik.enable=true"
      # Middleware
      - "traefik.http.middlewares.traefik.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      # HTTP ROUTER
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.xerogravity.space`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.middlewares=traefik"
      - "traefik.http.routers.traefik.service=api@internal"
      # HTTP TLS
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.tls.domains[0].main=local.xerogravity.space"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.local.xerogravity.space"
      - "traefik.http.routers.traefik.tls.domains[1].main=ts.xerogravity.space"
      - "traefik.http.routers.traefik.tls.domains[1].sans=*.ts.xerogravity.space"
      - "traefik.http.routers.traefik.tls.domains[2].main=cf.xerogravity.space"
      - "traefik.http.routers.traefik.tls.domains[2].sans=*.cf.xerogravity.space"