networks:
  default:
    name: tk-proxy
    external: true

services:
  neko:
    container_name: neko
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    env_file:
    - .env
    environment:
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: ${PASSWORD}
      NEKO_WEBRTC_EPR: "56000-56100"
      NEKO_WEBRTC_NAT1TO1: "192.168.18.2"
    image: ghcr.io/m1k1o/neko/nvidia-firefox:latest
    labels:
      traefik.enable: true
      traefik.http.routers.neko.entrypoints: https
      traefik.http.routers.neko.rule: Host(`neko.local.xerogravity.space`) || Host(`neko.cf.xerogravity.space`)
      traefik.http.routers.neko.service: neko
      traefik.http.routers.neko.tls: true
      traefik.http.services.neko.loadbalancer.server.port: 8080
    ports:
    - "56000-56100:56000-56100/udp"
    restart: unless-stopped
