networks:
  default:
    name: proxy
    external: true
    
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - BASE_URL=homarr.local.xerogravity.space
    ports:
      - 7575:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./container_data/homarr/configs:/app/data/configs
      - ./container_data/homarr/data:/data
      - ./container_data/homarr/icons:/app/public/icons
      - ./container_data/homarr/backgrounds:/app/public/imgs/backgrounds
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.routers.homarr.rule=Host(`homarr.local.xerogravity.space`)"
      - "traefik.http.routers.homarr.entrypoints=https"
      - "traefik.http.routers.homarr.service=homarr"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"