networks:
  default:
    name: tk-proxy
    external: true

services:
  homarr:
    container_name: homarr
    environment:
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
    image: ghcr.io/homarr-labs/homarr:latest
    labels:
      traefik.enable: true
      traefik.http.routers.homarr.entrypoints: https
      traefik.http.routers.homarr.rule: Host(`homarr.local.xerogravity.space`)
      traefik.http.routers.homarr.service: homarr
      traefik.http.routers.homarr.tls: true
      traefik.http.services.homarr.loadbalancer.server.port: 7575
    restart: unless-stopped
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: false
    - type: bind
      source: ./container_data/homarr/appdata
      target: /appdata
      read_only: false