networks:
  default:
    name: proxy
    external: true
    
services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/configs:/app/data/configs
      - ./data/icons:/app/public/icons
      - ./data/data:/data
      - ./data/images:/app/public/imgs/custom
    ports:
      - '7575:7575'
    environment:
      - BASE_URL=homarr.local.xerogravity.space
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.routers.homarr.entrypoints=https"
      - "traefik.http.routers.homarr.rule=Host(`homarr.local.xerogravity.space`)"
      - "traefik.http.routers.homarr.middlewares=secure-middlewares@file"
      - "traefik.http.routers.homarr.service=homarr"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"