services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr-configs:/app/data/configs
      - ./homarr-icons:/app/public/icons
      - ./homarr-data:/data
    ports:
      - '7575:7575'

networks:
  default:
    name: proxy
    external: true