networks:
  default:
    name: proxy
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9696:9696     # prowlarr-a
    volumes:
      - ./data/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md#wireguard
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      # Timezone for accurate log times
      - TZ=Asia/Kolkata
    restart: unless-stopped
    extra_hosts:
      - radarr:172.20.0.200
      - sonarr:172.20.0.201
      - flaresolverr:172.20.0.202
  
  prowlarr-a:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr-a
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./data/prowlarr-a:/config
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    
  # prowlarr-b:
  #   image: lscr.io/linuxserver/prowlarr:latest
  #   container_name: prowlarr-b
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Kolkata
  #   volumes:
  #     - ./data/prowlarr-b:/config
  #   ports:
  #     - 9697:9696
  #   restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./data/radarr:/config
      - /mnt/void/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.20.0.200

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./data/sonarr:/config
      - /mnt/void/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.20.0.201

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./data/bazarr:/config
      - /mnt/void/data/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./data/qbittorrent:/config
      - /mnt/void/data/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Asia/Kolkata
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.20.0.202

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    ports:
      - 5055:5055
    volumes:
      - ./data/jellyseerr:/app/config
      - /mnt/data/media:/data/media
    restart: unless-stopped