version: '3.8'

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    network_mode: container:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr-config:/config
  
  prowlarr-anime:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr-anime
    restart: always
    ports:
      - 9697:9696
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr-anime-config:/config
 
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      default:
        ipv4_address: 172.18.0.200
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr-config:/config
      - /mnt/blackhole/data:/data

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      default:
        ipv4_address: 172.18.0.201
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr-config:/config
      - /mnt/blackhole/data:/data
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - ./bazarr-config:/config
      - /mnt/blackhole/data/media:/data/media

  qbittorrent:
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      restart: unless-stopped
      ports:
        - 8080:8080
      environment:
        - PUID=1000
        - PGID=1000
        - UMASK=0022
        - TZ=Asia/Kolkata
        - WEBUI_PORT=8080
      volumes:
        - ./qbittorrent-config:/config
        - /mnt/blackhole/data/torrents:/data/torrents

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped 
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Asia/Kolkata

networks:
  default:
    name: chilflix_backend
    external: true