version: '3.8'

networks:
  chilflix_backend:
    driver: bridge
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: container:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - ./prowlarr-config:/config
    restart: always
  
  prowlarr2:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr2
    networks:
      - chilflix_backend
    ports:
      - 9697:9696
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - ./prowlarr2-config:/config
    restart: always
 
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      chilflix_backend:
        ipv4_address: 172.18.0.200
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - ./radarr-config:/config
      - /mnt/blackhole/movies:/movies
      - /mnt/blackhole/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      chilflix_backend:
        ipv4_address: 172.18.0.201
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - ./sonarr-config:/config
      - /mnt/blackhole/tv:/tv
      - /mnt/blackhole/downloads:/downloads
    restart: unless-stopped
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - chilflix_backend
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Asia/Kolkata
    volumes:
      - ./bazarr-config:/config
      - /mnt/blackhole/movies:/movies
      - /mnt/blackhole/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  qbittorrent:
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      networks:
        - chilflix_backend
      ports:
        - 9090:9090
      environment:
        - PUID=1000
        - PGID=1000
        - UMASK=0022
        - TZ=Asia/Kolkata
        - WEBUI_PORT=9090
      volumes:
        - ./qbittorrent-config:/config
        - /mnt/blackhole/downloads:/downloads
      restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
        - chilflix_backend
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Asia/Kolkata
    ports:
      - "8191:8191"
    restart: unless-stopped 
