networks:
  default:
    name: rxresume-network
  tk-proxy:
    name: tk-proxy
    external: true

services:
  postgres:
    container_name: rxresume-postgres
    env_file:
    - .env
    environment:
      POSTGRES_DB: rxresume
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: rxresume
    healthcheck:
      test:
      - 'CMD-SHELL'
      - 'pg_isready -U postgres -d postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./container_data/postgres/data
      target: /var/lib/postgresql/data
      read_only: false
  
  minio:
    command: server /data
    container_name: rxresume-minio
    env_file:
    - .env
    environment:
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
      MINIO_ROOT_USER: rxresume
    image: minio/minio
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./container_data/minio/data
      target: /data
      read_only: false
  
  chrome:
    container_name: rxresume-chrome
    environment:
      CONCURRENT: 10
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true
      TIMEOUT: 10000
      TOKEN: ${CHROME_TOKEN}
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
  
  rxresume:
    container_name: rxresume
    depends_on:
    - postgres
    - minio
    - chrome
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      CHROME_TOKEN: ${CHROME_TOKEN}
      CHROME_URL: ws://rxresume-chrome:3000
      DATABASE_URL: postgresql://rxresume:${DB_PASSWORD}@rxresume-postgres:5432/rxresume
      NODE_ENV: production
      PORT: 3005
      PUBLIC_URL: http://rxresume.local.xerogravity.space
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      STORAGE_ACCESS_KEY: rxresume
      STORAGE_BUCKET: default
      STORAGE_ENDPOINT: rxresume-minio
      STORAGE_PORT: 9000
      STORAGE_SECRET_KEY: ${STORAGE_PASSWORD}
      STORAGE_SKIP_BUCKET_CHECK: false
      STORAGE_URL: http://rxresume-minio:9000/default
      STORAGE_USE_SSL: false
    image: amruthpillai/reactive-resume:latest
    labels:
      traefik.enable: true
      traefik.http.routers.rxresume.entrypoints: https
      traefik.http.routers.rxresume.rule: Host(`rxresume.local.xerogravity.space`) || Host(`rxresume.ts.xerogravity.space`) || Host(`rxresume.cf.xerogravity.space`)
      traefik.http.routers.rxresume.service: rxresume
      traefik.http.routers.rxresume.tls: true
      traefik.http.services.rxresume.loadbalancer.server.port: 3005
    networks:
    - default
    - tk-proxy
    restart: unless-stopped
