services:
  cloudflared:
    command: tunnel --no-autoupdate run --token ${TOKEN}
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    network_mode: host
    restart: unless-stopped
