networks:
  default:
    name: tk-proxy
    external: true

services:
  gluetun:
    cap_add:
    - NET_ADMIN
    container_name: gluetun
    devices:
    - /dev/net/tun:/dev/net/tun
    environment:
      TZ: Asia/Kolkata
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
    extra_hosts:
    - radarr:172.18.0.200
    - sonarr:172.18.0.201
    - flaresolverr:172.18.0.202
    image: qmcgaw/gluetun:latest
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.entrypoints: https
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.local.xerogravity.space`)
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.routers.prowlarr.tls: true
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./container_data/gluetun/gluetun
      target: /gluetun
      read_only: false
