networks:
  default:
    name: beszel-network
  tk-proxy:
    name: tk-proxy
    external: true

services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:latest
    restart: unless-stopped
    volumes:
      - ./container_data/beszel/beszel_data:/beszel_data
    ports:
      - 8090:8090
    networks:
      - default
      - tk-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.local.xerogravity.space`)"
      - "traefik.http.routers.beszel.entrypoints=https"
      - "traefik.http.routers.beszel.service=beszel"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/void/.beszel:/extra-filesystems/sdb:ro
    env_file:
      - .env
    environment:
      - "KEY=${SSH_KEY}"