services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: 'unless-stopped'
    user: 1000:1000
    group_add:
      - '105'
    network_mode: host
    volumes:
      - /mnt/void/data/media:/media
      - ./container_data/jellyfin/cache:/cache
      - ./container_data/jellyfin/config:/config
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]