networks:
  default:
    name: proxy
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - '105'
    ports:
      - 8096:8096
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - /mnt/void/data/media:/media
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: 'unless-stopped'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.xerogravity.space`)"
      - "traefik.http.routers.jellyfin.middlewares=secure-middlewares@file"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"