services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: 'unless-stopped'
    user: 1000:1000
    group_add:
      - '105'
    network_mode: host
    volumes:
      - /mnt/void/data/media:/media
      - ./container_data/jellyfin/cache:/cache
      - ./container_data/jellyfin/config:/config
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  download-optimizer:
    container_name: jellyfin-download-optimizer
    image: fredrikburmester/streamyfin-optimized-versions-server:master
    environment:
      - NODE_ENV=development
      - JELLYFIN_URL=https://jellyfin.local.xerogravity.space
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
     - ./container_data/download-optimizer:/usr/src/app/cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin-optimizer.tls=true"
      - "traefik.http.routers.jellyfin-optimizer.rule=Host(`jellyfin-optimizer.local.xerogravity.space`) || Host(`jellyfin-optimizer.ts.xerogravity.space`)"
      - "traefik.http.routers.jellyfin-optimizer.entrypoints=https"
      - "traefik.http.routers.jellyfin-optimizer.service=jellyfin-optimizer"
      - "traefik.http.services.jellyfin-optimizer.loadbalancer.server.port=3000"