networks:
  default:
    name: tk-proxy
    external: true

services:
  dozzle:
    container_name: dozzle
    environment:
      DOZZLE_HOSTNAME: dozzle.local.xerogravity.space
    image: amir20/dozzle:latest
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.entrypoints: https
      traefik.http.routers.dozzle.rule: Host(`dozzle.local.xerogravity.space`)
      traefik.http.routers.dozzle.service: dozzle
      traefik.http.routers.dozzle.tls: true
      traefik.http.services.dozzle.loadbalancer.server.port: 8080
    restart: unless-stopped
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: false
