networks:
  default:
    name: tk-proxy
    external: true

services:
    cabernet:
        container_name: cabernet
        image: ghcr.io/cabernetwork/cabernet:latest
        environment:
          - TZ="Asia/Kolkata"
          - PUID=1000
          - PGID=1000
        restart: unless-stopped
        volumes:
          - ./container_data/cabernet/data:/app/data    
          - ./container_data/cabernet/plugins_ext:/app/plugins_ext
          - ./container_data/cabernet/secrets:/app/.cabernet
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.cabernet.tls=true"
          - "traefik.http.routers.cabernet.rule=Host(`cabernet.local.xerogravity.space`)"
          - "traefik.http.routers.cabernet.entrypoints=https"
          - "traefik.http.routers.cabernet.service=cabernet"
          - "traefik.http.services.cabernet.loadbalancer.server.port=6077"