networks:
  default:
    name: tk-proxy
    external: true

services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/void/data/media:/data/media
      - ./container_data/bazarr/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.local.xerogravity.space`)"
      - "traefik.http.routers.bazarr.entrypoints=https"
      - "traefik.http.routers.bazarr.service=bazarr"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"