networks:
  default:
    name: tk-proxy
    external: true

services:
  bazarr:
    container_name: bazarr
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Asia/Kolkata
    image: lscr.io/linuxserver/bazarr:latest
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.entrypoints: https
      traefik.http.routers.bazarr.rule: Host(`bazarr.local.xerogravity.space`)
      traefik.http.routers.bazarr.service: bazarr
      traefik.http.routers.bazarr.tls: true
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
    restart: unless-stopped
    volumes:
    - type: bind
      source: /mnt/void/data/media
      target: /data/media
      read_only: false
    - type: bind
      source: ./container_data/bazarr/config
      target: /config
      read_only: false
