networks:
  default:
    name: tk-proxy
    external: true

services:
  stirling-pdf:
    container_name: stirling-pdf
    environment:
      DOCKER_ENABLE_SECURITY: false
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
      LANGS: en_GB
    image: frooodle/s-pdf:latest
    labels:
      traefik.enable: true
      traefik.http.routers.stirling-pdf.entrypoints: https
      traefik.http.routers.stirling-pdf.rule: Host(`stirling-pdf.local.xerogravity.space`) || Host(`stirling-pdf.ts.xerogravity.space`) || Host(`stirling-pdf.cf.xerogravity.space`)
      traefik.http.routers.stirling-pdf.service: stirling-pdf
      traefik.http.routers.stirling-pdf.tls: true
      traefik.http.services.stirling-pdf.loadbalancer.server.port: 8080
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./container_data/stirling-pdf/tessdata
      target: /usr/share/tessdata
      read_only: false
    - type: bind
      source: ./container_data/stirling-pdf/configs
      target: /configs
      read_only: false
