networks:
  default:
    name: gamevault-network
  proxy:
    name: proxy
    external: true

services:
  postgres:
    container_name: gamevault-postgres
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=gamevault
      - POSTGRES_USER=gamevault
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./container_data/postgres/data:/var/lib/postgresql/data

  gamevault-backend:
    container_name: gamevault-backend
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=gamevault-postgres
      - DB_USERNAME=gamevault
      - DB_PASSWORD=${DB_PASSWORD}
      - METADATA_IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - METADATA_IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
    networks:
      - default
      - proxy
    volumes:
      - /mnt/void/games:/files
      - ./container_data/gamevault/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gamevault.tls=true"
      - "traefik.http.routers.gamevault.rule=Host(`gamevault.local.xerogravity.space`)"
      - "traefik.http.routers.gamevault.entrypoints=https"
      - "traefik.http.routers.gamevault.service=gamevault"
      - "traefik.http.services.gamevault.loadbalancer.server.port=8080"