services:
  gamevault-backend:
    container_name: gamevault-backend
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USERNAME=gamevault
      - DB_PASSWORD=${DB_PASSWORD}
      - RAWG_API_KEY=${RAWG_API_KEY}
      - SERVER_PORT=8082
    ports:
      - 8082:8082/tcp
    volumes:
      - /mnt/void/games:/files
      - ./container_data/gamevault/images:/images
  db:
    container_name: gamevault-db
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=gamevault
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=gamevault
    volumes:
      - ./container_data/postgres/data:/var/lib/postgresql/data