networks:
  default:
    name: tk-proxy
    external: true

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    labels:
      traefik.enable: true
      traefik.http.routers.uptime-kuma.entrypoints: https
      traefik.http.routers.uptime-kuma.rule: Host(`uptime-kuma.local.xerogravity.space`)
      traefik.http.routers.uptime-kuma.service: uptime-kuma
      traefik.http.routers.uptime-kuma.tls: true
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001
    restart: unless-stopped
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: false
    - type: bind
      source: ./container_data/uptime-kuma/data
      target: /app/data
      read_only: false
