services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=https"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.local.xerogravity.space`)"
      - "traefik.http.routers.uptime-kuma.middlewares=redirect-header@file,whitelisted-ips@file"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    networks:
      - proxy

networks:
  proxy:
    external: true
