services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9696:9696     # prowlarr-a
    volumes:
      - ./data:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md#wireguard
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      # Timezone for accurate log times
      - TZ=Asia/Kolkata
    restart: unless-stopped