networks:
  default:
    name: proxy
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9696:9696     # prowlarr-a
    volumes:
      - ./data:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md#wireguard
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      # Timezone for accurate log times
      - TZ=Asia/Kolkata
    restart: unless-stopped
    extra_hosts:
      - radarr:172.20.0.200
      - sonarr:172.20.0.201
      - flaresolverr:172.20.0.202
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr-a.tls=true"
      - "traefik.http.routers.prowlarr-a.entrypoints=https"
      - "traefik.http.routers.prowlarr-a.rule=Host(`prowlarr-a.local.xerogravity.space`)"
      - "traefik.http.routers.prowlarr-a.middlewares=redirect-header@file,whitelisted-ips@file"
      - "traefik.http.routers.prowlarr-a.service=prowlarr-a"
      - "traefik.http.services.prowlarr-a.loadbalancer.server.port=9696"