networks:
  default:
    name: proxy
    external: true

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9696:9696     # prowlarr-a
    volumes:
      - ./container_data/gluetun/gluetun:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - flaresolverr:172.20.0.202
      - radarr:172.20.0.200
      - sonarr:172.20.0.201
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr-a.tls=true"
      - "traefik.http.routers.prowlarr-a.rule=Host(`prowlarr-a.local.xerogravity.space`)"
      - "traefik.http.routers.prowlarr-a.entrypoints=https"
      - "traefik.http.routers.prowlarr-a.service=prowlarr-a"
      - "traefik.http.services.prowlarr-a.loadbalancer.server.port=9696"