networks:
  default:
    name: tk-proxy
    external: true

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
    volumes:
      - ./container_data/gluetun/gluetun:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - radarr:172.18.0.200
      - sonarr:172.18.0.201
      - flaresolverr:172.18.0.202
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.local.xerogravity.space`)"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"