networks:
  default:
    name: tk-proxy
    external: true

services:
  gluetun:
    cap_add:
    - NET_ADMIN
    container_name: gluetun
    devices:
    - /dev/net/tun:/dev/net/tun
    environment:
      TZ: Asia/Kolkata
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
    image: qmcgaw/gluetun:latest
    labels:
      traefik.enable: true
      traefik.http.routers.m3u-playlist-proxy.entrypoints: https
      traefik.http.routers.m3u-playlist-proxy.rule: Host(`m3u-playlist-proxy.local.xerogravity.space`)
      traefik.http.routers.m3u-playlist-proxy.service: m3u-playlist-proxy
      traefik.http.routers.m3u-playlist-proxy.tls: true
      traefik.http.services.m3u-playlist-proxy.loadbalancer.server.port: 4123
      # ------------
      traefik.http.routers.thetvapp-m3u.entrypoints: https
      traefik.http.routers.thetvapp-m3u.rule: Host(`thetvapp-m3u.local.xerogravity.space`)
      traefik.http.routers.thetvapp-m3u.service: thetvapp-m3u
      traefik.http.routers.thetvapp-m3u.tls: true
      traefik.http.services.thetvapp-m3u.loadbalancer.server.port: 4124
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./container_data/gluetun/gluetun
      target: /gluetun
      read_only: false

  m3u-playlist-proxy:
    container_name: m3u-playlist-proxy
    depends_on:
      - gluetun
    image: dtankdemp/m3u-playlist-proxy:latest
    network_mode: "service:gluetun"
    restart: unless-stopped
  
  thetvapp-m3u:
    container_name: thetvapp-m3u
    depends_on:
      - gluetun
    image: dtankdemp/thetvapp-m3u:latest
    network_mode: "service:gluetun"
    restart: unless-stopped