networks:
  default:
    name: proxy
    external: true

services: 
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - CAPTCHA_SOLVER=none
      - LOG_LEVEL=debug
      - LOG_HTML=false
      - TZ=Asia/Kolkata
    ports:
      - 8191:8191
    networks:
      default:
        ipv4_address: 172.20.0.202