networks:
  default:
    name: proxy
    external: true

services:
  whoami:
    container_name: whoami
    image: traefik/whoami
    ports:
      - 2001:2001
    command:
       - --port=2001
       - --name=i-am-ironman
    labels:
      - "traefik.enable=true"
      # middlewares
      - 'traefik.http.middlewares.whoami.headers.customRequestHeaders.Connection=Upgrade'
      - 'traefik.http.middlewares.whoami.headers.customRequestHeaders.Upgrade=websocket'
      # router
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local.xerogravity.space`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.middlewares=whoami"
      - "traefik.http.routers.whoami.service=whoami"
      # service
      - "traefik.http.services.whoami.loadbalancer.server.port=2001"