networks:
  default:
    name: tk-proxy
    external: true

services:
  autobrr:
    container_name: autobrr
    environment:
      TZ: Asia/Kolkata
    image: ghcr.io/autobrr/autobrr:latest
    labels:
      traefik.enable: true
      traefik.http.routers.autobrr.entrypoints: https
      traefik.http.routers.autobrr.rule: Host(`autobrr.local.xerogravity.space`)
      traefik.http.routers.autobrr.service: autobrr
      traefik.http.routers.autobrr.tls: true
      traefik.http.services.autobrr.loadbalancer.server.port: 7474
    ports:
    - 7474:7474
    restart: unless-stopped
    user: 1000:1000
    volumes:
    - type: bind
      source: ./container_data/autobrr/config
      target: /config
      read_only: false
  
  thelounge:
    container_name: thelounge
    image: ghcr.io/thelounge/thelounge:latest
    labels:
      traefik.enable: true
      traefik.http.routers.thelounge.entrypoints: https
      traefik.http.routers.thelounge.rule: Host(`thelounge.local.xerogravity.space`)
      traefik.http.routers.thelounge.service: thelounge
      traefik.http.routers.thelounge.tls: true
      traefik.http.services.thelounge.loadbalancer.server.port: 9000
    ports:
    - 9000:9000
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./container_data/thelounge/thelounge
      target: /var/opt/thelounge
      read_only: false
