networks:
  default:
    name: proxy
    external: true

services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./data/autobrr:/config
    ports:
      - 7474:7474
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autobrr.tls=true"
      - "traefik.http.routers.autobrr.entrypoints=https"
      - "traefik.http.routers.autobrr.rule=Host(`autobrr.local.xerogravity.space`)"
      - "traefik.http.routers.autobrr.middlewares=secure-middlewares@file"
      - "traefik.http.routers.autobrr.service=autobrr"
      - "traefik.http.services.autobrr.loadbalancer.server.port=7474"
  
  thelounge:
    container_name: thelounge
    ports:
      - 9000:9000
    volumes:
      - ./data/thelounge:/var/opt/thelounge
    restart: unless-stopped
    image: ghcr.io/thelounge/thelounge:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thelounge.tls=true"
      - "traefik.http.routers.thelounge.entrypoints=https"
      - "traefik.http.routers.thelounge.rule=Host(`thelounge.local.xerogravity.space`)"
      - "traefik.http.routers.thelounge.middlewares=secure-middlewares@file"
      - "traefik.http.routers.thelounge.service=thelounge"
      - "traefik.http.services.thelounge.loadbalancer.server.port=9000"
