networks:
  default:
    name: tk-proxy
    external: true

services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    restart: unless-stopped
    environment:
      - DOCKGE_STACKS_DIR=/home/debian/homelab
    volumes:
      - /home/debian/homelab:/home/debian/homelab
      - /var/run/docker.sock:/var/run/docker.sock
      - ./container_data/dockge/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.tls=true"
      - "traefik.http.routers.dockge.rule=Host(`dockge.local.xerogravity.space`)"
      - "traefik.http.routers.dockge.entrypoints=https"
      - "traefik.http.routers.dockge.service=dockge"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"