networks:
  default:
    name: tk-proxy
    external: true

services:
  dockge:
    container_name: dockge
    environment:
      DOCKGE_STACKS_DIR: /home/debian/homelab
    image: louislam/dockge:1
    labels:
      traefik.enable: true
      traefik.http.routers.dockge.entrypoints: https
      traefik.http.routers.dockge.rule: Host(`dockge.local.xerogravity.space`)
      traefik.http.routers.dockge.service: dockge
      traefik.http.routers.dockge.tls: true
      traefik.http.services.dockge.loadbalancer.server.port: 5001
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/debian/homelab
      target: /home/debian/homelab
      read_only: false
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: false
    - type: bind
      source: ./container_data/dockge/data
      target: /app/data
      read_only: false
