services:
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    ports:
      - "5454:5454"
    volumes:
      - ./data:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    environment:
      DN_API_KEY: ${API_KEY}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifiarr.tls=true"
      - "traefik.http.routers.notifiarr.entrypoints=https"
      - "traefik.http.routers.notifiarr.rule=Host(`notifiarr.local.xerogravity.space`)"
      - "traefik.http.routers.notifiarr.middlewares=redirect-header@file,whitelisted-ips@file"
      - "traefik.http.routers.notifiarr.service=notifiarr"
      - "traefik.http.services.notifiarr.loadbalancer.server.port=5454"

networks:
  default:
    name: proxy
    external: true