networks:
  default:
    name: tk-proxy
    external: true

services:
  notifiarr:
    container_name: notifiarr
    env_file:
    - .env
    environment:
      DN_API_KEY: ${API_KEY}
      TZ: Asia/Kolkata
    hostname: notifiarr
    image: golift/notifiarr
    labels:
      traefik.enable: true
      traefik.http.routers.notifiarr.entrypoints: https
      traefik.http.routers.notifiarr.rule: Host(`notifiarr.local.xerogravity.space`)
      traefik.http.routers.notifiarr.service: notifiarr
      traefik.http.routers.notifiarr.tls: true
      traefik.http.services.notifiarr.loadbalancer.server.port: 5454
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./container_data/notifiarr/config
      target: /config
      read_only: false
