networks:
  default:
    name: proxy
    external: true

services:
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DN_API_KEY=${API_KEY}
      - TZ=Asia/Kolkata
    volumes:
      - ./container_data/notifiarr/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifiarr.tls=true"
      - "traefik.http.routers.notifiarr.rule=Host(`notifiarr.local.xerogravity.space`)"
      - "traefik.http.routers.notifiarr.entrypoints=https"
      - "traefik.http.routers.notifiarr.service=notifiarr"
      - "traefik.http.services.notifiarr.loadbalancer.server.port=5454"